const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const state = { nodes: [], selected: 0, boot: null, menu: null };
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const clone = v => JSON.parse(JSON.stringify(v));
const cleanLines = v => String(v || '').split(/\r?\n/).map(x => x.trim()).filter(Boolean);
const blankNode = () => ({ id: '', root: '', root_font_size: 20, input_text_color: '#7eebff', input_text_prysm: false, picture_region_color: '#ff8a3d', connector_style: 'connector-1', ship_type: 'random', picture_enabled: false, picture_path: '', picture_asset_url: '', picture_asset_name: '', picture_caption: '', audio_enabled: false, audio_text: '', audio_voice: 'sot:en-US', questions_enabled: false, questions: [] });
const blankQuestion = () => ({ type: 'choice', card_mode: 'question', question: '', answer: '', wrong: [], audio: { mode: 'off' }, answer_audio: { mode: 'off', items: [] }, answer_info: { items: [] }, root_highlights: [], guidance_tree: { items: [] }, root_notice: { turns: [] }, select_targets: { root_ranges: [], regions: [] } });
const tip = text => `<span class="help" tabindex="0" data-tip="${esc(text)}">?</span>`;
const setStatus = text => { $('#status').textContent = text; };
const optionList = (items, selected, blank = '') => `${blank ? `<option value="">${esc(blank)}</option>` : ''}${(items || []).map(x => { const label = Array.isArray(x) ? x[0] : x; const value = Array.isArray(x) ? x[1] : x; return `<option value="${esc(value)}" ${value === selected ? 'selected' : ''}>${esc(label)}</option>`; }).join('')}`;
const moveItem = (items, index, direction) => { const target = index + direction; if (target < 0 || target >= items.length) return index; [items[index], items[target]] = [items[target], items[index]]; return target; };

function renderList() {
  $('#nodes').innerHTML = state.nodes.map((n, i) => `<div class="node-item ${i === state.selected ? 'active' : ''}" data-i="${i}"><div class="node-title"><b>Node ${i + 1}</b><span><button class="icon moveNode" data-dir="-1" title="Move up">↑</button><button class="icon moveNode" data-dir="1" title="Move down">↓</button></span></div><small>${esc((n.root || 'Untitled root').slice(0, 42))}</small></div>`).join('');
  $$('.node-item').forEach(item => item.addEventListener('click', e => { if (e.target.closest('button')) return; saveNode(); state.selected = +item.dataset.i; renderList(); renderEditor(); }));
  $$('.moveNode').forEach(button => button.onclick = e => { e.stopPropagation(); saveNode(); const index = +button.closest('.node-item').dataset.i; const next = moveItem(state.nodes, index, +button.dataset.dir); if (state.selected === index) state.selected = next; else if (state.selected === next) state.selected = index; renderList(); renderEditor(); });
}

function renderEditor() {
  const n = state.nodes[state.selected];
  if (!n) { $('#editor').innerHTML = '<div class="section"><h2>Chưa có node</h2></div>'; return; }
  const voices = state.boot.voices || [];
  $('#editor').innerHTML = `<div class="section"><h2>Root card <span class="muted">#${state.selected + 1}</span> ${tip('Bôi đen một đoạn Root rồi nhấp chuột phải để tạo highlight, câu hỏi hoặc linking card.')}</h2><div class="grid"><label class="field wide">Root text<textarea id="root" rows="5">${esc(n.root)}</textarea></label><label class="field">Root font size<input id="font" type="number" min="18" max="120" value="${n.root_font_size || 20}"></label><label class="field">Input color<input id="inputColor" type="color" value="${esc(n.input_text_color || '#7eebff')}"></label><label class="field">Picture region color<input id="regionColor" type="color" value="${esc(n.picture_region_color || '#ff8a3d')}"></label><label class="field">Ship<select id="ship">${optionList(state.boot.ship_types, n.ship_type)}</select></label><label class="field">Connector<select id="connector">${optionList(state.boot.connector_styles, n.connector_style)}</select></label><label class="field check"><span>Input effect ${tip('Prism tạo hiệu ứng pha lê nhiều màu cho đáp án nhập.')}</span><span><input id="prysm" type="checkbox" ${n.input_text_prysm ? 'checked' : ''}> Prism / Prysm</span></label><label class="field check"><span>Question cards</span><span><input id="qEnabled" type="checkbox" ${n.questions_enabled ? 'checked' : ''}> Enabled</span></label></div></div>
  <div class="section"><h2>Picture & audio cards</h2><div class="grid"><label class="field"><span><input id="picEnabled" type="checkbox" ${n.picture_enabled ? 'checked' : ''}> Picture enabled</span><input id="picFile" type="file" accept="image/*"></label><label class="field wide">Picture path / loaded asset<input id="picPath" value="${esc(n.picture_path || n.picture_asset_url)}"></label><label class="field wide">Caption<input id="picCaption" value="${esc(n.picture_caption)}"></label><label class="field wide">Audio text<textarea id="audioText" rows="2">${esc(n.audio_text)}</textarea></label><label class="field">Audio voice<select id="audioVoice">${optionList(voices, n.audio_voice)}</select></label><label class="field check"><span><input id="audioEnabled" type="checkbox" ${n.audio_enabled ? 'checked' : ''}> Audio enabled</span></label></div></div>
  <div class="section"><div class="row"><h2 class="push">Question cards <span class="muted">${(n.questions || []).length}</span></h2><button id="addQ">+ Add question</button></div><div id="questions">${(n.questions || []).map(questionView).join('')}</div></div>
  <div class="section compact"><h2>Node actions</h2><div class="row"><button id="deleteNode" class="ghost">Delete node</button><button id="duplicateNode" class="ghost">Duplicate node</button><span class="muted">Mọi thiết đặt nâng cao đều có popup biểu mẫu và menu chuột phải.</span></div></div>`;
  bindEditor(); bindContextMenus();
}

function questionView(q, i) {
  const alternatives = q.type === 'input' ? q.answers : q.type === 'select' ? q.tokens : q.wrong;
  return `<div class="question" data-q="${i}" tabindex="0"><div class="question-head"><span>Question ${i + 1} ${tip('Chuột phải để mở tất cả thiết đặt của câu hỏi.')}</span><span class="row"><button class="icon moveQ" data-dir="-1">↑</button><button class="icon moveQ" data-dir="1">↓</button><button class="tiny editQ">Edit</button><button class="tiny ghost delQ">Remove</button></span></div><div class="grid"><label class="field wide">Prompt<textarea data-k="question" rows="2">${esc(q.question)}</textarea></label><label class="field">Type<select data-k="type">${optionList(state.boot.question_types, q.type || 'choice')}</select></label><label class="field">Card mode<select data-k="card_mode"><option value="question" ${q.card_mode !== 'linking' ? 'selected' : ''}>Question card</option><option value="linking" ${q.card_mode === 'linking' ? 'selected' : ''}>Linking question card</option></select></label><label class="field">Order<input data-k="order" type="number" min="0" value="${q.order || 0}"></label><label class="field wide">Correct answer<textarea data-k="answer" rows="2">${esc(q.answer)}</textarea></label><label class="field wide">Wrong / accepted / select tokens ${tip('Mỗi dòng một mục. Ý nghĩa thay đổi theo loại câu hỏi.')}<textarea data-k="answers" rows="2">${esc((alternatives || []).join('\n'))}</textarea></label><div class="popup-grid full"><button class="subtle editFeature" data-kind="question_settings">Audio & explanations</button><button class="subtle editFeature" data-kind="root_highlights">Root highlights & linking</button><button class="subtle editFeature" data-kind="guidance_tree">Guidance tree</button><button class="subtle editFeature" data-kind="root_notice">Hologram notice</button><button class="subtle editFeature" data-kind="select_targets">Select targets</button></div><div class="feature-summary full">${featureSummary(q)}</div></div></div>`;
}

function featureSummary(q) {
  const guideCount = flattenTree(q.guidance_tree?.items || []).length;
  return [`Audio ${q.audio?.mode || 'off'}`, `${(q.answer_audio?.items || []).length} answer clips`, `${(q.answer_info?.items || []).length} explanations`, `${(q.root_highlights || []).length} highlights`, `${guideCount} guide cards`, `${(q.root_notice?.turns || []).length} notice turns`, `${(q.select_targets?.root_ranges || []).length + (q.select_targets?.regions || []).length} targets`].join(' · ');
}

function saveNode() {
  const n = state.nodes[state.selected];
  if (!n || !$('#root')) return;
  n.root = $('#root').value; n.root_font_size = +$('#font').value || 20; n.input_text_color = $('#inputColor').value; n.input_text_prysm = $('#prysm').checked; n.picture_region_color = $('#regionColor').value; n.ship_type = $('#ship').value; n.connector_style = $('#connector').value; n.picture_enabled = $('#picEnabled').checked; n.picture_caption = $('#picCaption').value; n.audio_enabled = $('#audioEnabled').checked; n.audio_text = $('#audioText').value; n.audio_voice = $('#audioVoice').value; n.questions_enabled = $('#qEnabled').checked;
  const path = $('#picPath').value; if (path.startsWith('data:')) { n.picture_asset_url = path; n.picture_path = ''; } else { n.picture_path = path; if (path) n.picture_asset_url = ''; }
  $$('.question').forEach((el, i) => { const q = n.questions[i]; q.question = $('[data-k="question"]', el).value; q.type = $('[data-k="type"]', el).value; q.card_mode = $('[data-k="card_mode"]', el).value; q.order = +$('[data-k="order"]', el).value || 0; q.answer = $('[data-k="answer"]', el).value; const vals = cleanLines($('[data-k="answers"]', el).value); if (q.type === 'input') q.answers = vals; else if (q.type === 'choice') q.wrong = vals; else q.tokens = vals; });
}

function bindEditor() {
  ['root', 'font', 'inputColor', 'regionColor', 'ship', 'connector', 'prysm', 'picEnabled', 'picCaption', 'audioText', 'audioVoice', 'audioEnabled', 'qEnabled'].forEach(id => document.getElementById(id)?.addEventListener('change', () => { saveNode(); renderList(); }));
  $('#addQ').onclick = () => { saveNode(); state.nodes[state.selected].questions.push(blankQuestion()); state.nodes[state.selected].questions_enabled = true; renderEditor(); };
  $$('.delQ').forEach(b => b.onclick = () => { saveNode(); state.nodes[state.selected].questions.splice(+b.closest('.question').dataset.q, 1); renderEditor(); });
  $$('.moveQ').forEach(b => b.onclick = () => { saveNode(); moveItem(state.nodes[state.selected].questions, +b.closest('.question').dataset.q, +b.dataset.dir); renderEditor(); });
  $$('.editQ').forEach(b => b.onclick = () => openQuestionPopup(+b.closest('.question').dataset.q));
  $$('.editFeature').forEach(b => b.onclick = () => openFeature(b.dataset.kind, +b.closest('.question').dataset.q));
  $('#deleteNode').onclick = () => { if (state.nodes.length === 1) return setStatus('Cần giữ ít nhất một node.'); state.nodes.splice(state.selected, 1); state.selected = Math.max(0, state.selected - 1); renderList(); renderEditor(); };
  $('#duplicateNode').onclick = () => { saveNode(); const copy = clone(state.nodes[state.selected]); copy.id = ''; state.nodes.splice(state.selected + 1, 0, copy); state.selected++; renderList(); renderEditor(); };
  $('#picFile').onchange = e => fileToDataUrl(e.target.files[0]).then(url => { if (!url) return; $('#picPath').value = url; $('#picEnabled').checked = true; saveNode(); setStatus('Đã nhúng ảnh vào node.'); });
}

function fileToDataUrl(file) { return new Promise(resolve => { if (!file) return resolve(''); const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = () => resolve(''); reader.readAsDataURL(file); }); }

function openQuestionPopup(index) {
  saveNode(); const q = state.nodes[state.selected].questions[index]; const alternatives = q.type === 'input' ? q.answers : q.type === 'select' ? q.tokens : q.wrong;
  openModal('Question fields', `<div class="grid"><label class="field full">Prompt<textarea id="mPrompt" rows="3">${esc(q.question)}</textarea></label><label class="field">Type<select id="mType">${optionList(state.boot.question_types, q.type)}</select></label><label class="field">Card mode<select id="mCard"><option value="question" ${q.card_mode !== 'linking' ? 'selected' : ''}>Question card</option><option value="linking" ${q.card_mode === 'linking' ? 'selected' : ''}>Linking question card</option></select></label><label class="field">Order<input id="mOrder" type="number" min="0" value="${q.order || 0}"></label><label class="field full">Correct answer<textarea id="mAnswer" rows="2">${esc(q.answer)}</textarea></label><label class="field full">Wrong choices / accepted answers / tokens<textarea id="mAlternatives" rows="5">${esc((alternatives || []).join('\n'))}</textarea></label></div>`, 'Save', () => { q.question = $('#mPrompt').value; q.type = $('#mType').value; q.card_mode = $('#mCard').value; q.order = +$('#mOrder').value || 0; q.answer = $('#mAnswer').value; const vals = cleanLines($('#mAlternatives').value); if (q.type === 'input') q.answers = vals; else if (q.type === 'choice') q.wrong = vals; else q.tokens = vals; renderEditor(); });
}

function answerTargets(q) {
  const values = [q.answer, ...(q.type === 'input' ? q.answers || [] : q.type === 'select' ? q.tokens || [] : q.wrong || [])].filter(Boolean);
  const seen = new Set(); const rows = values.filter(v => { const k = v.trim().toLowerCase(); if (!k || seen.has(k)) return false; seen.add(k); return true; }).map(v => ({ key: v, label: v, kind: 'answer' }));
  if (q.type === 'input') rows.push({ key: '__typed_correct__', label: 'Typed answer correct', kind: 'typed' }, { key: '__typed_wrong__', label: 'Typed answer wrong', kind: 'typed' });
  return rows;
}

function questionSettingsForm(q) {
  const audioItems = new Map((q.answer_audio?.items || []).map(x => [String(x.text || '').toLowerCase(), x]));
  const infoItems = new Map((q.answer_info?.items || []).map(x => [String(x.text || '').toLowerCase(), x]));
  const rows = [{ key: '__question__', label: 'Question prompt', kind: 'question' }, ...answerTargets(q)];
  return `<p class="muted">Thiết lập riêng audio và thẻ giải thích cho prompt, đáp án đúng, đáp án sai/chấp nhận và phản hồi input.</p><div class="setting-table">${rows.map(row => { const audio = row.kind === 'question' ? q.audio || {} : audioItems.get(row.key.toLowerCase()) || {}; const info = infoItems.get(row.key.toLowerCase()) || {}; const typed = row.kind === 'typed'; return `<div class="setting-row" data-target="${esc(row.key)}" data-kind="${row.kind}"><b>${esc(row.label)}</b><label class="field">Audio text<textarea data-s="audio_text" rows="2" ${typed ? 'disabled' : ''}>${esc(audio.audio_text || audio.text || (row.kind === 'question' ? q.question : row.key))}</textarea></label><label class="field">Audio mode<select data-s="audio_mode" ${typed ? 'disabled' : ''}>${optionList(state.boot.question_audio_modes, typed ? 'off' : audio.mode || 'off')}</select></label><label class="field">Audio voice<select data-s="audio_voice" ${typed ? 'disabled' : ''}>${optionList(state.boot.voices, audio.voice || 'sot:en-US')}</select></label><label class="field">Explanation<textarea data-s="info_text" rows="2" ${row.kind === 'question' ? 'disabled' : ''}>${esc(info.info_text || '')}</textarea></label><label class="field">Info mode<select data-s="info_mode" ${row.kind === 'question' ? 'disabled' : ''}>${optionList(state.boot.question_info_modes, info.mode || 'audio')}</select></label><label class="field">Info voice<select data-s="info_voice" ${row.kind === 'question' ? 'disabled' : ''}>${optionList(state.boot.voices, info.voice || 'edge:vi-VN-NamMinhNeural')}</select></label></div>`; }).join('')}</div>`;
}

function saveQuestionSettings(q, modal) {
  const audioItems = [], infoItems = [];
  $$('.setting-row', modal).forEach(row => { const target = row.dataset.target, kind = row.dataset.kind; const audioText = $('[data-s="audio_text"]', row)?.value || ''; const audioMode = $('[data-s="audio_mode"]', row)?.value || 'off'; const audioVoice = $('[data-s="audio_voice"]', row)?.value || ''; const infoText = $('[data-s="info_text"]', row)?.value || ''; const infoMode = $('[data-s="info_mode"]', row)?.value || 'audio'; const infoVoice = $('[data-s="info_voice"]', row)?.value || '';
    if (kind === 'question') { q.audio = { ...(q.audio || {}), mode: audioMode, voice: audioVoice, audio_text: audioText }; return; }
    if (kind !== 'typed' && (audioMode !== 'off' || audioText !== target)) audioItems.push({ text: target, audio_text: audioText || target, mode: audioMode, voice: audioVoice });
    if (infoText) infoItems.push({ text: target, info_text: infoText, mode: infoMode, voice: infoVoice });
  });
  q.answer_audio = { mode: audioItems.length ? 'click' : 'off', items: audioItems }; q.answer_info = { items: infoItems };
}

function highlightCard(item = {}, index = 0) {
  const pq = item.picture_question || {};
  return `<div class="highlight-card edit-card" data-highlight="${index}"><div class="card-head"><b>Highlight ${index + 1}</b><span><button class="icon hMove" data-dir="-1">↑</button><button class="icon hMove" data-dir="1">↓</button><button class="icon danger hRemove">×</button></span></div><div class="grid"><label class="field wide">Selected Root text<input data-h="text" value="${esc(item.text || '')}"></label><label class="field">Start<input data-h="start" type="number" min="0" value="${item.start || 0}"></label><label class="field">End<input data-h="end" type="number" min="0" value="${item.end || 0}"></label><button class="subtle useRootSelection">Use current Root selection</button><label class="field">Style<select data-h="style">${optionList(state.boot.highlight_styles, item.style || 'style-1')}</select></label><label class="field">Render<select data-h="render">${optionList(state.boot.highlight_render_modes, item.render || 'text')}</select></label><label class="field">Color<input data-h="color" type="color" value="${esc(item.color || '#46f0d7')}"></label><label class="field check"><span>Camera</span><span><input data-h="camera_focus" type="checkbox" ${item.camera_focus ? 'checked' : ''}> Pan view</span></label><label class="field full">Teaching note<textarea data-h="info" rows="2">${esc(item.info || '')}</textarea></label></div><details><summary>Linking picture question ${tip('Tạo thẻ linking nối với highlight, ảnh hoặc các vùng ảnh được vẽ.')}</summary><div class="grid inset"><label class="field wide">Linking question text<textarea data-pq="text" rows="2">${esc(pq.text || '')}</textarea></label><label class="field">Anchor<select data-pq="anchor">${optionList(state.boot.picture_question_anchors, pq.anchor || 'highlight')}</select></label><label class="field">Placement<select data-pq="placement">${optionList(state.boot.picture_question_placements, pq.placement || 'auto')}</select></label><label class="field">Region color<input data-pq="region_color" type="color" value="${esc(pq.region_color || '#ff8a3d')}"></label></div><div class="region-host" data-regions="${esc(JSON.stringify(pq.regions || []))}"></div></details></div>`;
}

function highlightForm(q, node) {
  return `<p class="muted">Bôi đen trực tiếp trong Root preview rồi thêm range. Mỗi highlight có thể tạo linking question và vùng ảnh riêng.</p><label class="field">Root preview<textarea id="rootSelectionSource" rows="4">${esc(node.root)}</textarea></label><div id="highlightRows">${(q.root_highlights?.length ? q.root_highlights : [{}]).map(highlightCard).join('')}</div><button id="addHighlight" class="subtle">+ Highlight</button>`;
}

function bindHighlightForm(modal, node) {
  const render = () => { $$('.highlight-card', modal).forEach(card => initRegionEditor($('.region-host', card), currentPictureSource(node), card._regions || JSON.parse($('.region-host', card).dataset.regions || '[]'), $('[data-pq="region_color"]', card))); bindCards(); };
  const bindCards = () => {
    $$('.highlight-card', modal).forEach(card => {
      const host = $('.region-host', card); if (!host._regionData) initRegionEditor(host, currentPictureSource(node), JSON.parse(host.dataset.regions || '[]'), $('[data-pq="region_color"]', card));
      $('.useRootSelection', card).onclick = () => { const source = $('#rootSelectionSource', modal), start = source.selectionStart, end = source.selectionEnd; if (end <= start) return setStatus('Hãy bôi đen một đoạn Root preview trước.'); $('[data-h="text"]', card).value = source.value.slice(start, end); $('[data-h="start"]', card).value = start; $('[data-h="end"]', card).value = end; };
      $('.hRemove', card).onclick = () => { if ($$('.highlight-card', modal).length === 1) { $$('input,textarea', card).forEach(x => { if (x.type !== 'color') x.value = ''; }); host._regionData.regions = []; host._regionData.draw(); } else card.remove(); renumberCards(modal, '.highlight-card', 'Highlight'); };
      $$('.hMove', card).forEach(b => b.onclick = () => moveCardDom(card, +b.dataset.dir));
    });
  };
  $('#addHighlight', modal).onclick = () => { $('#highlightRows', modal).insertAdjacentHTML('beforeend', highlightCard({}, $$('.highlight-card', modal).length)); bindCards(); const card = $$('.highlight-card', modal).at(-1); initRegionEditor($('.region-host', card), currentPictureSource(node), [], $('[data-pq="region_color"]', card)); };
  render();
}

function collectHighlights(modal) {
  return $$('.highlight-card', modal).map(card => { const get = key => $(`[data-h="${key}"]`, card); const pqText = $('[data-pq="text"]', card).value.trim(); const regions = $('.region-host', card)._regionData?.regions || []; const result = { text: get('text').value, start: +get('start').value || 0, end: +get('end').value || 0, style: get('style').value, render: get('render').value, color: get('color').value, info: get('info').value }; if (get('camera_focus').checked) result.camera_focus = true; if (pqText || regions.length) result.picture_question = { text: pqText, anchor: $('[data-pq="anchor"]', card).value, placement: $('[data-pq="placement"]', card).value, region_color: $('[data-pq="region_color"]', card).value, regions: clone(regions) }; return result; }).filter(x => x.text || x.picture_question);
}

function currentPictureSource(node) { return node.picture_asset_url || (String(node.picture_path || '').startsWith('data:') ? node.picture_path : ''); }

function initRegionEditor(host, imageSrc, regions = [], colorInput = null) {
  if (!host || host._regionData) return;
  host.innerHTML = `<div class="region-workspace"><div class="region-stage"><img alt="Picture region source" src="${esc(imageSrc)}"><canvas></canvas><div class="no-image">${imageSrc ? 'Loading image…' : 'Hãy chọn ảnh cho node trước khi vẽ vùng.'}</div></div><div class="region-side"><div class="region-list"></div><div class="row"><button class="tiny deleteRegion">Delete selected</button><button class="tiny ghost clearRegions">Clear all</button></div><small class="muted">Kéo chuột trên ảnh để tạo hình chữ nhật. Nhấp vùng để chọn.</small></div></div>`;
  const canvas = $('canvas', host), img = $('img', host), list = $('.region-list', host), data = { regions: clone(regions), selected: -1, drag: null, draw: null };
  const resize = () => { const rect = img.getBoundingClientRect(); canvas.width = Math.max(1, Math.round(rect.width)); canvas.height = Math.max(1, Math.round(rect.height)); canvas.style.width = `${rect.width}px`; canvas.style.height = `${rect.height}px`; $('.no-image', host).hidden = !!(img.complete && img.naturalWidth); draw(); };
  const draw = () => { const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height); data.regions.forEach((r, i) => { const color = r.color || colorInput?.value || '#ff8a3d'; ctx.fillStyle = `${color}44`; ctx.strokeStyle = color; ctx.lineWidth = i === data.selected ? 4 : 2; ctx.fillRect(r.x * canvas.width, r.y * canvas.height, r.w * canvas.width, r.h * canvas.height); ctx.strokeRect(r.x * canvas.width, r.y * canvas.height, r.w * canvas.width, r.h * canvas.height); ctx.fillStyle = color; ctx.fillRect(r.x * canvas.width + 4, r.y * canvas.height + 4, 28, 20); ctx.fillStyle = '#061112'; ctx.font = 'bold 12px sans-serif'; ctx.fillText(r.label || String(i + 1), r.x * canvas.width + 12, r.y * canvas.height + 19); }); if (data.drag) { ctx.setLineDash([7, 5]); ctx.strokeStyle = colorInput?.value || '#ff8a3d'; ctx.strokeRect(data.drag.x * canvas.width, data.drag.y * canvas.height, data.drag.w * canvas.width, data.drag.h * canvas.height); ctx.setLineDash([]); } renderRegionList(); };
  const renderRegionList = () => { list.innerHTML = data.regions.map((r, i) => `<button class="region-item ${i === data.selected ? 'active' : ''}" data-i="${i}"><b>${esc(r.label || String(i + 1))}</b><span>${r.x.toFixed(3)}, ${r.y.toFixed(3)} · ${r.w.toFixed(3)} × ${r.h.toFixed(3)}</span><input type="color" value="${esc(r.color || colorInput?.value || '#ff8a3d')}" title="Region color"></button>`).join('') || '<span class="muted">Chưa có vùng.</span>'; $$('.region-item', list).forEach(item => { item.onclick = e => { if (e.target.type === 'color') return; data.selected = +item.dataset.i; draw(); }; $('input', item).oninput = e => { data.regions[+item.dataset.i].color = e.target.value; draw(); }; }); };
  const point = e => { const r = canvas.getBoundingClientRect(); return { x: Math.max(0, Math.min(1, (e.clientX - r.left) / r.width)), y: Math.max(0, Math.min(1, (e.clientY - r.top) / r.height)) }; };
  canvas.onpointerdown = e => { const p = point(e); const hit = data.regions.map((r, i) => ({ r, i })).reverse().find(x => p.x >= x.r.x && p.x <= x.r.x + x.r.w && p.y >= x.r.y && p.y <= x.r.y + x.r.h); if (hit) { data.selected = hit.i; draw(); return; } data.drag = { sx: p.x, sy: p.y, x: p.x, y: p.y, w: 0, h: 0 }; canvas.setPointerCapture(e.pointerId); };
  canvas.onpointermove = e => { if (!data.drag) return; const p = point(e); data.drag.x = Math.min(data.drag.sx, p.x); data.drag.y = Math.min(data.drag.sy, p.y); data.drag.w = Math.abs(p.x - data.drag.sx); data.drag.h = Math.abs(p.y - data.drag.sy); draw(); };
  canvas.onpointerup = () => { if (!data.drag) return; if (data.drag.w >= .01 && data.drag.h >= .01) { const i = data.regions.length + 1; data.regions.push({ id: `r${i}`, label: String.fromCharCode(64 + Math.min(i, 26)), shape: 'rect', x: +data.drag.x.toFixed(5), y: +data.drag.y.toFixed(5), w: +data.drag.w.toFixed(5), h: +data.drag.h.toFixed(5), color: colorInput?.value || '#ff8a3d' }); data.selected = data.regions.length - 1; } data.drag = null; draw(); };
  $('.deleteRegion', host).onclick = () => { if (data.selected >= 0) data.regions.splice(data.selected, 1); data.selected = Math.min(data.selected, data.regions.length - 1); draw(); };
  $('.clearRegions', host).onclick = () => { data.regions = []; data.selected = -1; draw(); };
  img.onload = resize; if (img.complete) setTimeout(resize); new ResizeObserver(resize).observe(img); data.draw = draw; host._regionData = data; draw();
}

function selectTargetsForm(q, node) {
  const data = q.select_targets || {};
  return `<p class="muted">Chọn trực tiếp chữ trong Root preview hoặc kéo vùng trên ảnh. Không cần nhập tọa độ bằng tay.</p><label class="field">Root preview<textarea id="targetRootSource" rows="5">${esc(node.root)}</textarea></label><div class="row"><button id="addRootRange" class="subtle">+ Add selected Root text</button><button id="clearRootRanges" class="ghost">Clear text targets</button></div><div id="rootRangeList">${(data.root_ranges || []).map((r, i) => rootRangeCard(r, i)).join('')}</div><h3>Picture regions</h3><label class="field region-color">Default region color<input id="targetRegionColor" type="color" value="${esc(data.region_color || node.picture_region_color || '#ff8a3d')}"></label><div id="targetRegionHost" class="region-host"></div>`;
}
function rootRangeCard(r, i) { return `<div class="range-card" data-range="${i}"><b>${i + 1}. ${esc(r.text || '')}</b><span>${r.start || 0} → ${r.end || 0}</span><button class="icon danger removeRange">×</button><input type="hidden" data-r="text" value="${esc(r.text || '')}"><input type="hidden" data-r="start" value="${r.start || 0}"><input type="hidden" data-r="end" value="${r.end || 0}"></div>`; }
function bindSelectTargets(modal, q, node) { const list = $('#rootRangeList', modal); $('#addRootRange', modal).onclick = () => { const source = $('#targetRootSource', modal), start = source.selectionStart, end = source.selectionEnd; if (end <= start) return setStatus('Hãy bôi đen đoạn Root cần chọn.'); list.insertAdjacentHTML('beforeend', rootRangeCard({ start, end, text: source.value.slice(start, end) }, $$('.range-card', list).length)); bindRangeRemove(); }; $('#clearRootRanges', modal).onclick = () => { list.innerHTML = ''; }; const bindRangeRemove = () => $$('.removeRange', list).forEach(b => b.onclick = () => b.closest('.range-card').remove()); bindRangeRemove(); initRegionEditor($('#targetRegionHost', modal), currentPictureSource(node), q.select_targets?.regions || [], $('#targetRegionColor', modal)); }
function collectSelectTargets(modal, node) { const rootRanges = $$('.range-card', modal).map(card => ({ text: $('[data-r="text"]', card).value, start: +$('[data-r="start"]', card).value, end: +$('[data-r="end"]', card).value })); const regions = $('#targetRegionHost', modal)._regionData?.regions || []; const payload = { root_ranges: rootRanges, regions: clone(regions), region_color: $('#targetRegionColor', modal).value }; if (rootRanges.length === 1) payload.root_text = rootRanges[0].text; return payload; }

function noticeForm(q) { const turns = q.root_notice?.turns?.length ? q.root_notice.turns : [{}]; return `<p class="muted">Mỗi lượt nói có nhân vật, giọng, avatar, tiếng Anh và hỗ trợ tiếng Việt riêng.</p><div id="noticeRows">${turns.map(noticeCard).join('')}</div><button id="addNotice" class="subtle">+ Speaker turn</button>`; }
function noticeCard(turn = {}, index = 0) { const avatar = turn.avatar?.url || turn.avatar_path || ''; return `<div class="notice-card edit-card" data-turn="${index}"><div class="card-head"><b>Turn ${index + 1}</b><span><button class="icon nMove" data-dir="-1">↑</button><button class="icon nMove" data-dir="1">↓</button><button class="icon danger nRemove">×</button></span></div><div class="notice-grid"><div class="avatar-preview">${avatar ? `<img src="${esc(avatar)}">` : '<span>Avatar</span>'}</div><div class="grid"><label class="field">Character<input data-n="speaker" value="${esc(turn.speaker || '')}"></label><label class="field">Voice<select data-n="voice">${optionList(state.boot.voices, turn.voice || '', 'Typing only | no voice')}</select></label><label class="field wide">Avatar<input data-n="avatarFile" type="file" accept="image/*"><input data-n="avatar" value="${esc(avatar)}" placeholder="Image URL or choose file"></label><label class="field full">English<textarea data-n="english" rows="3">${esc(turn.english || '')}</textarea></label><label class="field full">Vietnamese<textarea data-n="vietnamese" rows="2">${esc(turn.vietnamese || '')}</textarea></label></div></div></div>`; }
function bindNoticeForm(modal) { const bind = () => $$('.notice-card', modal).forEach(card => { $('.nRemove', card).onclick = () => { if ($$('.notice-card', modal).length === 1) $$('input,textarea', card).forEach(x => { if (x.type !== 'file') x.value = ''; }); else card.remove(); renumberCards(modal, '.notice-card', 'Turn'); }; $$('.nMove', card).forEach(b => b.onclick = () => moveCardDom(card, +b.dataset.dir)); $('[data-n="avatarFile"]', card).onchange = async e => { const url = await fileToDataUrl(e.target.files[0]); if (!url) return; $('[data-n="avatar"]', card).value = url; $('.avatar-preview', card).innerHTML = `<img src="${esc(url)}">`; }; $('[data-n="avatar"]', card).onchange = e => { $('.avatar-preview', card).innerHTML = e.target.value ? `<img src="${esc(e.target.value)}">` : '<span>Avatar</span>'; }; }); $('#addNotice', modal).onclick = () => { $('#noticeRows', modal).insertAdjacentHTML('beforeend', noticeCard({}, $$('.notice-card', modal).length)); bind(); }; bind(); }
function collectNotice(modal) { return { turns: $$('.notice-card', modal).map(card => { const avatar = $('[data-n="avatar"]', card).value; const turn = { speaker: $('[data-n="speaker"]', card).value, voice: $('[data-n="voice"]', card).value, english: $('[data-n="english"]', card).value, vietnamese: $('[data-n="vietnamese"]', card).value }; if (avatar) turn.avatar = { url: avatar, name: 'avatar' }; return turn; }).filter(x => x.english || x.vietnamese || x.speaker || x.avatar) }; }

function flattenTree(items, prefix = []) { const out = []; (items || []).forEach((node, i) => { const path = [...prefix, i]; out.push({ node, path, depth: path.length - 1 }); out.push(...flattenTree(node.children || [], path)); }); return out; }
function nodeAt(items, path) { let list = items, node = null; for (const i of path) { node = list[i]; if (!node) return null; list = node.children || (node.children = []); } return node; }
function listAt(items, path) { if (path.length === 1) return items; return nodeAt(items, path.slice(0, -1)).children || (nodeAt(items, path.slice(0, -1)).children = []); }
function guidanceForm() { return `<p class="muted">Cây lồng nhau: thêm child/sibling, đổi thứ tự, tạo nhánh đáp án và chọn chế độ info/choice/input.</p><div class="guide-layout"><div><div id="guideTree" class="guide-tree"></div><div class="row"><button id="guideChild" class="tiny">+ Child</button><button id="guideSibling" class="tiny">+ Sibling</button><button id="guideUp" class="icon">↑</button><button id="guideDown" class="icon">↓</button><button id="guideRemove" class="tiny ghost">Remove</button></div></div><div id="guideDetail"></div></div>`; }
function bindGuidance(modal, q) {
  const items = clone(q.guidance_tree?.items || []); if (!items.length) items.push({ text: q.answer || 'Answer', children: [] }); let selected = [0];
  const saveDetail = () => { const node = nodeAt(items, selected); const detail = $('#guideDetail', modal); if (!node || !detail.dataset.ready) return; const top = selected.length === 1; if (top) node.text = $('[data-g="title"]', detail).value; else node.title = $('[data-g="title"]', detail).value; node.body = $('[data-g="body"]', detail).value; node.main = $('[data-g="main"]', detail).value; node.answer_option = $('[data-g="answer_option"]', detail).value; node.type = $('[data-g="type"]', detail).value; node.question = $('[data-g="question"]', detail).value; node.answer = $('[data-g="answer"]', detail).value; const choices = cleanLines($('[data-g="choices"]', detail).value); if (node.type === 'input') node.answers = choices; else node.wrong = choices; };
  const render = () => { const flat = flattenTree(items); $('#guideTree', modal).innerHTML = flat.map(x => `<button class="guide-node ${x.path.join('.') === selected.join('.') ? 'active' : ''}" data-path="${x.path.join('.')}"><span style="--depth:${x.depth}">${esc(x.node.text || x.node.title || 'Untitled card')}</span><small>${esc(x.node.type || 'info')}</small></button>`).join(''); $$('.guide-node', modal).forEach(b => b.onclick = () => { saveDetail(); selected = b.dataset.path.split('.').map(Number); render(); }); const node = nodeAt(items, selected); if (!node) return; $('#guideDetail', modal).innerHTML = `<div class="grid"><label class="field wide">Card title / answer branch<input data-g="title" value="${esc(node.text || node.title || '')}"></label><label class="field">Mode<select data-g="type"><option value="info" ${(node.type || 'info') === 'info' ? 'selected' : ''}>Info card</option><option value="choice" ${node.type === 'choice' ? 'selected' : ''}>Choice question</option><option value="input" ${node.type === 'input' ? 'selected' : ''}>Input question</option></select></label><label class="field full">Body / explanation<textarea data-g="body" rows="3">${esc(node.body || '')}</textarea></label><label class="field full">Connector / main text<textarea data-g="main" rows="2">${esc(node.main || '')}</textarea></label><label class="field wide">Answer option from parent<input data-g="answer_option" value="${esc(node.answer_option || '')}"></label><label class="field full">Question prompt<textarea data-g="question" rows="2">${esc(node.question || '')}</textarea></label><label class="field wide">Correct answer<input data-g="answer" value="${esc(node.answer || '')}"></label><label class="field full">Wrong choices / accepted input answers<textarea data-g="choices" rows="3">${esc(((node.type === 'input' ? node.answers : node.wrong) || []).join('\n'))}</textarea></label><button id="guideAnswerChildren" class="subtle full">Create child cards from answers</button></div>`; $('#guideDetail', modal).dataset.ready = '1'; $('#guideAnswerChildren', modal).onclick = () => { saveDetail(); const current = nodeAt(items, selected); const values = [current.answer, ...cleanLines($('[data-g="choices"]', $('#guideDetail', modal)).value)].filter(Boolean); current.children = values.map(v => ({ title: v, answer_option: v, body: '' })); render(); }; };
  $('#guideChild', modal).onclick = () => { saveDetail(); const node = nodeAt(items, selected); (node.children ||= []).push({ title: 'New child card' }); selected = [...selected, node.children.length - 1]; render(); };
  $('#guideSibling', modal).onclick = () => { saveDetail(); const list = listAt(items, selected); const index = selected.at(-1) + 1; list.splice(index, 0, selected.length === 1 ? { text: 'New answer branch' } : { title: 'New sibling card' }); selected = [...selected.slice(0, -1), index]; render(); };
  $('#guideRemove', modal).onclick = () => { const list = listAt(items, selected); list.splice(selected.at(-1), 1); if (!items.length) items.push({ text: q.answer || 'Answer' }); selected = [Math.min(selected[0], items.length - 1)]; render(); };
  $('#guideUp', modal).onclick = () => { saveDetail(); const list = listAt(items, selected); const next = moveItem(list, selected.at(-1), -1); selected = [...selected.slice(0, -1), next]; render(); };
  $('#guideDown', modal).onclick = () => { saveDetail(); const list = listAt(items, selected); const next = moveItem(list, selected.at(-1), 1); selected = [...selected.slice(0, -1), next]; render(); };
  modal._guidance = { items, saveDetail }; render();
}

function openFeature(kind, index) {
  saveNode(); const node = state.nodes[state.selected], q = node.questions[index]; let body = '', after = null, saver = null, title = '';
  if (kind === 'question_settings') { title = 'Question audio & explanations'; body = questionSettingsForm(q); saver = modal => saveQuestionSettings(q, modal); }
  if (kind === 'root_highlights') { title = 'Root highlights & linking cards'; body = highlightForm(q, node); after = modal => bindHighlightForm(modal, node); saver = modal => { q.root_highlights = collectHighlights(modal); }; }
  if (kind === 'select_targets') { title = 'Select question targets'; body = selectTargetsForm(q, node); after = modal => bindSelectTargets(modal, q, node); saver = modal => { q.select_targets = collectSelectTargets(modal, node); if (q.type === 'select') { const words = q.select_targets.root_ranges.flatMap(x => cleanLines(x.text.replace(/\s+/g, '\n'))); if (words.length) { q.tokens = words; q.answer = words.join(' '); } } }; }
  if (kind === 'root_notice') { title = 'Hologram notice dialogue'; body = noticeForm(q); after = bindNoticeForm; saver = modal => { q.root_notice = collectNotice(modal); }; }
  if (kind === 'guidance_tree') { title = 'Guidance tree'; body = guidanceForm(); after = modal => bindGuidance(modal, q); saver = modal => { modal._guidance.saveDetail(); q.guidance_tree = { items: modal._guidance.items }; }; }
  openModal(title, body, 'Save', modal => { saver(modal); renderEditor(); }, after, kind === 'root_highlights' || kind === 'guidance_tree' ? 'large' : '');
}

function moveCardDom(card, direction) { const sibling = direction < 0 ? card.previousElementSibling : card.nextElementSibling; if (!sibling) return; if (direction < 0) card.parentElement.insertBefore(card, sibling); else card.parentElement.insertBefore(sibling, card); renumberCards(card.closest('.modal'), card.classList.contains('notice-card') ? '.notice-card' : '.highlight-card', card.classList.contains('notice-card') ? 'Turn' : 'Highlight'); }
function renumberCards(root, selector, label) { $$(selector, root).forEach((card, i) => { $('.card-head b', card).textContent = `${label} ${i + 1}`; }); }

function openModal(title, body, saveText, onSave, afterOpen = null, size = '') {
  closeModal(); const backdrop = document.createElement('div'); backdrop.className = 'modal-backdrop'; backdrop.innerHTML = `<section class="modal ${size}"><div class="modal-head"><h2>${esc(title)}</h2><button class="closeModal ghost">×</button></div><div class="modal-body">${body}</div><div class="modal-foot"><button class="closeModal ghost">Cancel</button><button id="modalSave">${esc(saveText)}</button></div></section>`; document.body.appendChild(backdrop); const modal = $('.modal', backdrop); $$('.closeModal', modal).forEach(b => b.onclick = closeModal); $('#modalSave', modal).onclick = () => { onSave(modal); closeModal(); setStatus('Đã lưu thiết đặt popup.'); }; afterOpen?.(modal); return modal;
}
function closeModal() { $('.modal-backdrop')?.remove(); }

function selectedRootPayload() { const root = $('#root'); if (!root) return null; const start = root.selectionStart, end = root.selectionEnd; return end > start ? { start, end, text: root.value.slice(start, end) } : null; }
function bindContextMenus() {
  $('#root')?.addEventListener('contextmenu', e => { e.preventDefault(); saveNode(); const selected = selectedRootPayload(), node = state.nodes[state.selected]; const items = [];
    items.push(['Create question from selected Root', () => { const q = blankQuestion(); if (selected) q.answer = selected.text; node.questions.push(q); node.questions_enabled = true; renderEditor(); openQuestionPopup(node.questions.length - 1); }]);
    node.questions.forEach((q, i) => items.push([`Add selection to Question ${i + 1}`, () => { if (!selected) return setStatus('Hãy bôi đen Root text trước.'); (q.root_highlights ||= []).push({ ...selected, color: '#46f0d7', style: 'style-2', render: 'block' }); openFeature('root_highlights', i); }]));
    items.push(['Create linking picture question', () => { const q = blankQuestion(); q.card_mode = 'linking'; q.answer = selected?.text || ''; q.root_highlights = selected ? [{ ...selected, color: '#46f0d7', style: 'style-2', render: 'block', picture_question: { text: '', anchor: 'highlight', placement: 'auto' } }] : []; node.questions.push(q); node.questions_enabled = true; renderEditor(); openFeature('root_highlights', node.questions.length - 1); }]);
    items.push(['Picture & audio settings', () => $('.section:nth-child(2)')?.scrollIntoView({ behavior: 'smooth' })]); showMenu(e.clientX, e.clientY, items);
  });
  $$('.question').forEach(el => el.addEventListener('contextmenu', e => { e.preventDefault(); const i = +el.dataset.q; showMenu(e.clientX, e.clientY, [['Edit question fields', () => openQuestionPopup(i)], ['Audio & answer explanations', () => openFeature('question_settings', i)], ['Root highlights / linking card', () => openFeature('root_highlights', i)], ['Guidance tree', () => openFeature('guidance_tree', i)], ['Hologram notice', () => openFeature('root_notice', i)], ['Select Root / picture targets', () => openFeature('select_targets', i)], ['Move question up', () => { saveNode(); moveItem(state.nodes[state.selected].questions, i, -1); renderEditor(); }], ['Move question down', () => { saveNode(); moveItem(state.nodes[state.selected].questions, i, 1); renderEditor(); }], ['Duplicate question', () => { saveNode(); state.nodes[state.selected].questions.splice(i + 1, 0, clone(state.nodes[state.selected].questions[i])); renderEditor(); }], ['Delete question', () => { saveNode(); state.nodes[state.selected].questions.splice(i, 1); renderEditor(); }]]); }));
}
function showMenu(x, y, items) { state.menu?.remove(); const menu = document.createElement('div'); menu.className = 'context-menu'; menu.style.left = `${Math.min(x, innerWidth - 285)}px`; menu.style.top = `${Math.min(y, innerHeight - Math.min(520, items.length * 43 + 18))}px`; menu.innerHTML = items.map((item, i) => `<button data-mi="${i}">${esc(item[0])}</button>`).join(''); items.forEach((item, i) => $(`[data-mi="${i}"]`, menu).onclick = () => { item[1](); menu.remove(); }); document.body.appendChild(menu); state.menu = menu; setTimeout(() => document.addEventListener('click', () => menu.remove(), { once: true })); }

function splitQuestionLine(line) { const delimiter = line.includes('\t') ? '\t' : line.includes('|') ? '|' : line.includes(';') ? ';' : ','; return line.split(delimiter).map(x => x.trim()).filter(Boolean); }
async function importQuestions(file) { if (!file) return; saveNode(); const lines = (await file.text()).split(/\r?\n/); let added = 0; for (const raw of lines) { const columns = splitQuestionLine(raw); if (columns.length < 2) continue; const q = blankQuestion(); q.type = columns.length > 2 ? 'choice' : 'input'; q.question = columns[0]; q.answer = columns[1]; if (q.type === 'choice') q.wrong = columns.slice(2); state.nodes[state.selected].questions.push(q); added++; } state.nodes[state.selected].questions_enabled = true; renderEditor(); setStatus(`Đã nhập ${added} câu hỏi từ TXT.`); }
function documentData() { saveNode(); return { title: $('#title').value, order: $('#order').value, rewards: { crystal: { name: $('#crystalName').value, use: $('#crystalUse').value } }, nodes: clone(state.nodes) }; }
async function build(preview = false) { try { setStatus('Đang build...'); $('#log').textContent = ''; const response = await fetch('/api/build', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...documentData(), direct_payload: preview }) }); const data = await response.json(); if (data.error) throw Error(data.error); $('#log').textContent = (data.logs || []).join('\n'); if (preview) { if (!data.preview_url) throw Error('Không tạo được preview HTML.'); window.open(data.preview_url, '_blank'); } else { const raw = atob(data.space_q), blob = new Blob([Uint8Array.from(raw, c => c.charCodeAt(0))], { type: 'application/octet-stream' }), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = data.filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); } setStatus(preview ? 'Preview đã mở.' : 'Đã build và tải file Space_Q.'); } catch (error) { setStatus(`Lỗi: ${error.message}`); } }

$('#addNode').onclick = () => { saveNode(); state.nodes.push(blankNode()); state.selected = state.nodes.length - 1; renderList(); renderEditor(); };
$('#build').onclick = () => build(false); $('#preview').onclick = () => build(true); $('#importTxt').onchange = e => importQuestions(e.target.files[0]);
$('#loadFile').onchange = async e => { const file = e.target.files[0]; if (!file) return; setStatus('Đang đọc Space_Q...'); const response = await fetch('/api/load', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: await file.text() }) }); const data = await response.json(); if (data.error) return setStatus(`Lỗi: ${data.error}`); const payload = data.payload || {}, crystal = (payload.rewards || payload.reward || {}).crystal || {}; $('#title').value = payload.title || payload.t || file.name.replace(/\.Space_Q$/i, ''); $('#order').value = (payload.order || payload.o) === 'shuffle' ? 'shuffle' : 'sequence'; $('#crystalName').value = crystal.name || 'Prism Crystal'; $('#crystalUse').value = crystal.use || 'Stores learning energy for future item upgrades.'; state.nodes = data.nodes || []; state.selected = 0; renderList(); renderEditor(); setStatus(`Đã load ${state.nodes.length} node.`); };
fetch('/api/bootstrap').then(r => r.json()).then(boot => { state.boot = boot; state.nodes = [blankNode()]; renderList(); renderEditor(); });
